### ISSUE TITLE
Support pagination

### ISSUE THREAD

**Issue by zeke** [millette/librarian-api#3]
I'd like to collect all the `dependent_repositories` for a given npm package.

``` sh
curl -i -s "https://libraries.io/api/npm/electron-prebuilt/dependent_repositories/?per_page=1" | grep Total

Total: 4960
```

This library needs a way to paginate. @millette any thoughts on how that should look/work?

**Comment by millette** [comment]
> Nobody uses that library anymore, it's too popular. - _(like the restaurant quote)_

I can fetch the whole lot in one call, respecting rate limits, which is my preferred way. Or I could provide paging options.

I could probably reuse my [gh bookworm](https://github.com/millette/rollodeqc-gh-bookworm).

**Comment by zeke** [comment]
fetching the whole lot would be nice for the end user, but it could get quite slow for project with a lot of dependencies:

5000 results, 100 per page, 1 request/second = 50 seconds minimum

**Comment by millette** [comment]
It's going to be slow paging or automatically. But yeah, paging is always nice to have. I'll implement both later this week (not before Wednesday). PRs are always appreciated :-)

Honestly, I didn't give much thought to this module, I needed it for another quick project so I threw that together, but I plan on using it further in the near term. It could see a rewrite then.

**Comment by zeke** [comment]
> Honestly, I didn't give much thought to this module

That's okay! I know it's rough around the edges, but I would rather collaborate with someone else on a libraries.io client than write and maintain my own. ❄️

**Comment by millette** [comment]
I appreciate the help and guidance. Time just freed up for me today, I'm taking a stab at it now.

**Comment by millette** [comment]
Here we go. No automatic paging just yet, but per_page and page query parameters are supported.

I wanted to refactor the module, it's very redundant as it stands... Maybe next pass.

**Comment by zeke** [comment]
Thank you!
